feature:
  - changed-files:
      - any-glob-to-any-file:
          [
            'packages/puppeteer-extra-plugin-recaptcha/src/index.ts',
            'packages/puppeteer-extra-plugin-recaptcha/src/provider/*',
            'packages/puppeteer-extra-plugin-recaptcha/redme.md',
          ]
  - base-branch: ['master']
  - head-branch: ['recaptchaCapMonster']
